### PR TITLE
Rebase to Alpine 3.19

### PR DESCRIPTION
**Pull request by nemchik**

### CODE REVIEW

**Review by thespad — CHANGES_REQUESTED** [review]
Not viable until the node 20 on Debian build issues are resolved.

Also I have a big chunk of build improvements to integrate from the glitch branch when it comes to rebasing dev/stable.

**Comment by nemchik** [comment]
> Not viable until the node 20 on Debian build issues are resolved.
> 
> Also I have a big chunk of build improvements to integrate from the glitch branch when it comes to rebasing dev/stable.

Should be resolved now (node issue)

Do you want to commit additional changes from glitch to this branch or make a separate PR?

**Comment by thespad** [comment]
I'm going to do some local tests to see if I can include the changes yet, I suspect I won't be able to until the next upstream point release incorporates the new stuff that's already in glitch.

**Comment by thespad** [comment]
Nope, won't work with the current stable branch. Going to close these PRs and will open new ones when the next release hits dev and then stable and roll everything in together.

**Pull request closed without merging**
