### PR TITLE
Rebase to Alpine 3.19

### PR DESCRIPTION
**Pull request by nemchik**
https://github.com/nodejs/docker-node/issues/1912
Also potential ruby issue

### CODE REVIEW

**Review by thespad — CHANGES_REQUESTED** [review]
Not viable until the node 20 on Debian build issues are resolved.

Also I have a big chunk of build improvements to integrate from the glitch branch when it comes to rebasing dev/stable.

**Comment by nemchik** [comment]
> Not viable until the node 20 on Debian build issues are resolved.
> 
> Also I have a big chunk of build improvements to integrate from the glitch branch when it comes to rebasing dev/stable.

Should be resolved now

Same as prior comment (do you want to commit here or separate PR?)

**Comment by thespad** [comment]
Develop won't build until the next upstream release (there's a broken dep that they fixed in the stable releases but didn't backport to beta/RCs (obviously)).

**Comment by thespad** [comment]
Will open a new PR once there's a working dev build

**Pull request closed without merging**
